---
title: "Extract metadata for GBIF Datasets"
author: "Lien Reyserhove"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Load libraries:

```{r}
library(tidyverse)
library(lubridate)
library(janitor)
library(here)
library(rgbif)
```

Extract fields of interest:

```{r get_metadata}
alienCSI_dataset <- rgbif::datasets(uuid = "8a309be4-939e-4874-a6ba-6ebee4ebeaac")$data
```

Extract information:

```{r}
metadata <-
  tibble(
    `title` = toString(alienCSI_dataset$title),
    `type` =  toString(alienCSI_dataset$type),
    `metadata language` = toString(alienCSI_dataset$lang),
    `data language` = toString(alienCSI_dataset$dataLanguage),
    `Update frequency` = toString(alienCSI_dataset$maintenanceUpdateFrequency),
    `Data license` = toString(alienCSI_dataset$license),
    `Description` = toString(alienCSI_dataset$description),
    `Geographic Coverage - Description` = toString(alienCSI_dataset$geographicCoverages[1]),
    `Geographic Coverage - BoundBox` = toString(alienCSI_dataset$geographicCoverages[2]),
    `Taxonomic COverage` = toString(alienCSI_dataset$taxonomicCoverages),
    `Temporal coverage - Type` = toString(alienCSI_dataset$temporalCoverages[1]),
    `Keyword Thesaurus` = toString(alienCSI_dataset$keywordCollections$thesaurus),
    `Keyword List` = toString(alienCSI_dataset$keywordCollections$keywords),
    `Project Data - Title` = toString(alienCSI_dataset$project$title),
    `Project Data - ID` = toString(alienCSI_dataset$project$identifier),
    `Project Data - Funding` = toString(alienCSI_dataset$project$funding),
    `Project Data - Abstract` = toString(alienCSI_dataset$project$abstract),
    `Project Data - Study Area Desc` = toString(alienCSI_dataset$project$studyAreaDescription),
    `Project Data - Design Desc` = toString(alienCSI_dataset$project$designDescription),
    `Sampling methods - Study Extent` = toString(alienCSI_dataset$samplingDescription$studyExtent),
    `Sampling methods - Sampling Description` = toString(alienCSI_dataset$samplingDescription$sampling),
    `Sampling methods - Quality Control` = toString(alienCSI_dataset$samplingDescription$qualityControl),
    `Sampling methods - Step description` = toString(alienCSI_dataset$samplingDescription$methodSteps),
    `Citations - Resource citation` = toString(alienCSI_dataset$citation$text),
    `Collection data` = toString(alienCSI_dataset$collections),
    `Additional metadata - Resource logo URL` = toString(alienCSI_dataset$logoUrl),
    `Additional metadata - Purpose` = toString(alienCSI_dataset$purpose),
    `Additional metadata - Maintenance description` = toString(alienCSI_dataset$maintenanceDescription)
    ) %>% transpose()
metadata
```



